name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go: [1.17]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...

#    - name: Covert Coverage Results
#      run: |
#        pip install coveragepy-lcov
#        coveragepy-lcov --data_file_path .coverage --output_file_path lcov.info
#
#    - name: Coveralls
#      uses: coverallsapp/github-action@1.1.3
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        path-to-lcov: lcov.info
