name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go: [1.17]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Test with coverageprofile
      run: go test -v -coverprofile=profile.cov ./...

    - name: Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
        flag-name: Go-${{ matrix.go }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
